### ISSUE TITLE
New plugin request

### ISSUE THREAD

**Issue by ghost** [nimah79/rapidleech-plugins#5]
Please create new plugin for multifilemirror.com

**Comment by 1mahdimf** [comment]
سلام لطفا برای آپلود تو سایت پیکوفایل هم یه فکری بکنید.

**Comment by nimah79** [comment]
> سلام لطفا برای آپلود تو سایت پیکوفایل هم یه فکری بکنید.

That's already added!

**Comment by nimah79** [comment]
> Please create new plugin for multifilemirror.com

That's already added!
